In [1]:
import numpy as np


In [2]:
a=([3,2],[4,5])
a

([3, 2], [4, 5])

In [3]:
np.ndim(a)

2

In [4]:
arr=np.array([[[3,4]]])
arr

array([[[3, 4]]])

In [5]:
arr.ndim

3

In [6]:
arr.shape

(1, 1, 2)

In [7]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr=np.linspace(1,10,10)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [9]:
arr=np.logspace(1,3)
arr

array([  10.        ,   10.98541142,   12.06792641,   13.25711366,
         14.56348478,   15.9985872 ,   17.57510625,   19.30697729,
         21.20950888,   23.29951811,   25.59547923,   28.11768698,
         30.88843596,   33.93221772,   37.2759372 ,   40.94915062,
         44.98432669,   49.41713361,   54.28675439,   59.63623317,
         65.51285569,   71.9685673 ,   79.06043211,   86.85113738,
         95.40954763,  104.81131342,  115.13953993,  126.48552169,
        138.94954944,  152.64179672,  167.68329368,  184.20699693,
        202.35896477,  222.29964825,  244.20530945,  268.26957953,
        294.70517026,  323.74575428,  355.64803062,  390.69399371,
        429.19342601,  471.48663635,  517.94746792,  568.9866029 ,
        625.05519253,  686.648845  ,  754.31200634,  828.64277285,
        910.29817799, 1000.        ])

In [10]:
a=np.zeros(6)
a

array([0., 0., 0., 0., 0., 0.])

In [11]:
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
a=np.full(10,2)
a

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
a=np.full([2,5],7)
a

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [14]:
arr=np.random.rand(10)
arr

array([0.2621978 , 0.2222428 , 0.21396179, 0.82942282, 0.19635554,
       0.7686973 , 0.70408642, 0.31078505, 0.3411658 , 0.54266927])

In [15]:
arr=np.random.rand(3,5)
arr

array([[0.78034813, 0.48943756, 0.59512725, 0.2578904 , 0.1270654 ],
       [0.81300043, 0.12049039, 0.06301436, 0.00453424, 0.23229629],
       [0.20480502, 0.03888446, 0.84573784, 0.26809499, 0.13421685]])

In [16]:
arr=np.random.randint(10,100)
arr

87

In [18]:
def square (x):
    return x*x
vfunc=np.vectorize(square)
vfunc(arr)

array(7569)

In [27]:
arr=np.array([1, np.nan , 2,np.nan , 6])
print(np.isnan(arr))

[False  True False  True False]


In [28]:
arr

array([ 1., nan,  2., nan,  6.])

In [33]:
print(np.isnan(arr))

[False  True False  True False]
